Repository near-in-minutes/frontend, pull requests merged in 2021-07, with the labels that each got.

#72 update package and added prettier.
  .prettierrc.js
  package.json
  src/App.vue
  src/components/CollectionsList.vue
  src/components/SingleVideoTitle.vue
  src/components/SummaryStatistics.vue
  src/components/VideosList.vue
  src/composables/useAuthors.js
  src/i18n/de.json
  src/pages/AboutPage.vue
  src/pages/ContributePage.vue
  src/pages/ListAuthorsPage.vue
  src/pages/SingleAuthorPage.vue
  src/pages/SingleCollectionPage.vue
  src/router/index.js
Labels: fix

#73 Create node.js.yml
  .github/workflows/node.js.yml
Labels: fix

#61 Fix: Text color were not visible
  src/pages/SingleAuthorPage.vue
Labels: fix

#74 Update SingleVideoPage.vue
  src/pages/SingleVideoPage.vue
Labels: bug

#83 TRANSLATE: enrich the tr.json
  src/i18n/tr.json
Labels: documentation
